export {default as SignIn} from './signin/signin'
export {default as ConfirmationPage} from './confirtmation/confirmation-page'
export {default as ConfirmOrMenu} from './confirm-or-menu/confirm-or-menu'
export {default as Dashboard} from './dashboard/dashboard'
export {default as Workers} from './resource/employees/index/index'
export {default as EmployeeDt} from './resource/employees/index/employee-dt'
export {default as EmployeeForm} from './resource/employees/create/employee-form'
