AllCops:
  Exclude:
    # - 'spec/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/swagger_helper.rb'
    - 'spec/support/api/schemas/**/*'
    - 'bin/**/*'
    - 'config/puma.rb'
    - 'config/initializers/rswag_api.rb'
    - 'config/initializers/rswag-ui.rb'
    - 'db/schema.rb'
    - 'Guardfile'
  TargetRubyVersion: 3.0.1
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'path', 'post', 'get', 'put', 'response', 'patch']

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
